# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.CharField(max_length=14, unique=True, verbose_name='')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='')),
                ('status', models.CharField(choices=[('open', '开立'), ('submit', '提交'), ('commit', '审核'), ('cancel', '作废')], max_length=1, verbose_name='')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('fax_number', models.CharField(max_length=64, verbose_name='传真号码')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Brand')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Customer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Department')),
                ('order_taker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_order_taker', to='base_data.Staff')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='OrderParm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='')),
                ('parm_type', models.CharField(choices=[('manual', '手工录入'), ('relate_item', '关联项目')], max_length=32, verbose_name='')),
                ('parm_class', models.CharField(choices=[('char', '字符串'), ('int', '整数'), ('float', '小数')], max_length=16)),
                ('parm_len', models.IntegerField(default=32, verbose_name='')),
                ('relate_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.BaseItem')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='')),
                ('desc', models.CharField(max_length=128, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='sale_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.SaleType'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_salesman', to='base_data.Staff'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Tax'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.InvoiceHeader'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.Material'),
        ),
    ]
