# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='品牌名称')),
                ('img', models.ImageField(upload_to='', verbose_name='品牌图片')),
            ],
            options={
                'verbose_name': '经营品牌',
                'verbose_name_plural': '经营品牌',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='颜色名称')),
                ('img', models.ImageField(upload_to='', verbose_name='颜色图片')),
            ],
            options={
                'verbose_name': '颜色',
                'verbose_name_plural': '颜色',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='币别名称')),
                ('symbol', models.CharField(max_length=16, unique=True, verbose_name='货币符号')),
            ],
            options={
                'verbose_name': '币种',
                'verbose_name_plural': '币种',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户简称')),
                ('fullname', models.CharField(max_length=128, unique=True, verbose_name='客户全称')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('we_chat', models.CharField(blank=True, max_length=32, verbose_name='微信号')),
                ('contact_man', models.CharField(max_length=32, verbose_name='联系人')),
                ('contact_number', models.CharField(max_length=64, verbose_name='联系电话')),
                ('fax_number', models.CharField(max_length=64, verbose_name='传真号码')),
                ('credit_limit', models.BooleanField(default=False, verbose_name='信用检查')),
                ('credit', models.DecimalField(blank=True, decimal_places=3, max_digits=15, verbose_name='信用额度')),
                ('brand', models.ManyToManyField(related_name='customer_brand', to='basedata.Brand')),
            ],
            options={
                'verbose_name': '客户资料',
                'verbose_name_plural': '客户资料',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='客户类别名称')),
            ],
            options={
                'verbose_name': '客户类别',
                'verbose_name_plural': '客户类别',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('encoder', models.CharField(max_length=32, verbose_name='物料编码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='物料名称')),
                ('specification', models.CharField(max_length=64, verbose_name='规格')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='销售单价')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='采购单价')),
                ('stock_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='库存单价')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.CreateModel(
            name='MaterialOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='物料来源名称')),
            ],
            options={
                'verbose_name': '物料来源',
                'verbose_name_plural': '物料来源',
            },
        ),
        migrations.CreateModel(
            name='MaterialParmGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='参数组名称')),
            ],
            options={
                'verbose_name': '物料参数组',
                'verbose_name_plural': '物料参数组',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='物料类别名称')),
            ],
            options={
                'verbose_name': '物料类别',
                'verbose_name_plural': '物料类别',
            },
        ),
        migrations.CreateModel(
            name='Parm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='参数名称(符号)')),
                ('parm_name', models.CharField(max_length=32, unique=True, verbose_name='参数名称')),
                ('input_type', models.CharField(choices=[('manual', '手工录入'), ('relate_item', '关联项目')], max_length=16, verbose_name='')),
                ('parm_type', models.CharField(choices=[('char', '字符串'), ('int', '整数'), ('float', '小数')], max_length=8)),
                ('input_len', models.IntegerField(verbose_name='录入长度')),
                ('relate_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '参数',
                'verbose_name_plural': '参数',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='销售类型名称')),
            ],
            options={
                'verbose_name': '销售类型',
                'verbose_name_plural': '销售类型',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='系列名称')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.Brand')),
            ],
            options={
                'verbose_name': '产品系列',
                'verbose_name_plural': '产品系列',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='职员名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.Department')),
            ],
            options={
                'verbose_name': '职员',
                'verbose_name_plural': '职员',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='税别名称')),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=15, unique=True, verbose_name='税率')),
            ],
            options={
                'verbose_name': '税种',
                'verbose_name_plural': '税种',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=32, null=True, verbose_name='修改人')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否有效')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='单位名称')),
                ('symbol', models.CharField(max_length=16, unique=True, verbose_name='单位符号')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.AddField(
            model_name='materialparmgroup',
            name='parm',
            field=models.ManyToManyField(to='basedata.Parm'),
        ),
        migrations.AddField(
            model_name='material',
            name='aux_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aux_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='main_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.MaterialOrigin'),
        ),
        migrations.AddField(
            model_name='material',
            name='parm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Material_parm_group', to='basedata.MaterialParmGroup'),
        ),
        migrations.AddField(
            model_name='material',
            name='produce_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produce_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='purchase_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='sale_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.Series'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_unit', to='basedata.Unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.MaterialType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cus_order_taker', to='basedata.Staff'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cus_salesman', to='basedata.Staff'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedata.CustomerType'),
        ),
    ]
